# Generated by Django 5.0.4 on 2024-07-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabeledData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regu", models.CharField(max_length=100)),
                ("nilai_absen", models.DecimalField(decimal_places=2, max_digits=5)),
                ("nilai_jurnal", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "nilai_kuisioner",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Regu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_regu", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JurnalHarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("tanggal", models.DateField()),
                ("skp_tahunan", models.CharField(max_length=100)),
                ("jurnal_harian", models.TextField()),
                ("jumlah", models.IntegerField()),
                ("satuan", models.CharField(max_length=50)),
                ("jam_mulai", models.TimeField()),
                ("jam_selesai", models.TimeField()),
                ("nilai", models.DecimalField(decimal_places=2, max_digits=5)),
                ("komentar", models.TextField()),
                ("tanggal_isi", models.DateField(auto_now_add=True)),
                ("lampiran", models.FileField(upload_to="lampiran/")),
                (
                    "regu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.regu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Absensi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nip", models.CharField(max_length=20)),
                ("tanggal", models.DateField()),
                ("nama", models.CharField(max_length=100)),
                ("unit_kerja", models.CharField(max_length=100)),
                ("terlambat", models.IntegerField(default=0)),
                ("pulang_cepat", models.IntegerField(default=0)),
                ("terlambat_menit", models.IntegerField(default=0)),
                ("pulang_cepat_menit", models.IntegerField(default=0)),
                ("tanpa_keterangan", models.IntegerField(default=0)),
                ("terlambat_izin", models.IntegerField(default=0)),
                ("pulang_cepat_izin", models.IntegerField(default=0)),
                ("lupa_absen_masuk", models.IntegerField(default=0)),
                ("lupa_absen_pulang", models.IntegerField(default=0)),
                ("full", models.IntegerField(default=0)),
                ("half", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                (
                    "regu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.regu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("point_regu", models.IntegerField()),
                (
                    "regu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.regu"
                    ),
                ),
            ],
        ),
    ]
